name: EC2 Static Deploy

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 작동

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 1. GitHub의 모든 파일(web, css 등)을 EC2의 임시 폴더로 복사
      - name: Copy All Files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ec2-user/"

      # 2. EC2 내부에서 파일을 엔진엑스 경로로 옮기고 엔진엑스 재시작
      
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Nginx 폴더의 권한을 완전히 풉니다.
            sudo chmod -R 777 /var/www/html

            # 2. 기존에 있던 옛날 파일들을 모두 지웁니다.
            sudo rm -rf /var/www/html/*

            # 3. web 폴더 '안에 있는 내용물만' /var/www/html로 복사합니다.
            # (web/* 처럼 뒤에 별표를 붙이는 것이 중요합니다)
            sudo cp -rf /home/ec2-user/web/* /var/www/html/

            # 4. Nginx를 재시작하여 변경사항을 반영합니다.
            sudo systemctl restart nginx